---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild-iso
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
#*####################################
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - helix
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
#*####################################
#  - type: default-flatpaks@v1
#    notify: true # Send notification after install/uninstall is finished (true/false)
#    system:
#      # If no repo information is specified, Flathub will be used by default
#      install:
#        - org.mozilla.firefox
#        - org.gnome.Loupe
#        - page.kramo.Cartridges
#      remove:
#        - org.gnome.eog

  - type: default-flatpaks
    configurations:
      - install:
          - com.bitwarden.desktop               # Bitwarden
#          - com.brave.Browser                   # Brave Browser
#          - com.mattjakeman.ExtensionManager    # Extension Manager
#          - com.github.tchx84.Flatseal          # FlatSeal
#          - it.mijorus.gearlever                # Gearlever
#          - org.gnome.TextEditor                # Gnome Text Editor
#          - org.gnome.Loupe                     # Image Viewer
#          - io.gitlab.librewolf-community       # LibreWolf
#          - io.missioncenter.MissionCenter      # Mission Center
#          - com.rustdesk.RustDesk               # Rustdesk
#          - org.gnome.seahorse.Application      # Seahorse
#          - dev.deedles.Trayscale               # Tray Scale
#          - io.github.flattool.Warehouse        # Warehouse 

#*####################################

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

#*#####################################
  - type: files
    files:
      - source: system  # copies `files/system/*` (* means everything inside it) into your image's root folder `/`
        destination: /
